### ISSUE TITLE
Documentation about supported transaction database formats missing/lacking

### ISSUE THREAD

**Issue by tpoikela** [Minres/SCViewer#2]
The link http://www.accellera.org/activities/committees/systemc-verification is no longer valid. Also, SystemC SCV documentation does not describe their database format, just some API calls you can do to produce such a database. I don't have installation of SystemC to try it out, and it would be better to have some documentation for the format anyway.

Could you add some examples of supported transaction database formats (preferably text-based, non-binary formats)? I'm working on uvm-python library, and would like to add support for dumping SCViewer compatible databases, at least in text format.

**Comment by eyck** [comment]
THX for the hint
The format written by the SCV is the only text-based format supported by SCViewer. Text based formats tend to produce huge files sizes, in one of the prpjects we are talking about TBs...
You are right, SCV specifies the API and come with a reference implementation of a backend. But practically SCV is dead. 
Given these two facts we implemented a tx database format call fast transaction recording (FTR). A reference implementation can be found at https://github.com/Minres/LWTR4SC. There is also the documentation of the database format: https://github.com/Minres/LWTR4SC/blob/main/src/lwtr/cbor/chunked_writer.h#L414, which is [CBOR ](https://cbor.io/) based. There are a few implementations for PYthon available (see https://cbor.io/impls.html). One of them is used in an example dumping a FTR database: https://github.com/Minres/LWTR4SC/blob/main/contrib/dump_ftr.py

Maybe it is a good idea to provide a Python package for creating those database files...

**Comment by tpoikela** [comment]
Thanks a lot for the links. I went through them, but I could not find documentation about the FTR format itself in those files. I think it's spread around the source code itself, so not easy to reverse-engineer. The CBOR format documentation is very useful, thanks for that, and seems to be quite simple to add to Python.

**Comment by eyck** [comment]
The comment at https://github.com/Minres/LWTR4SC/blob/main/src/lwtr/cbor/chunked_writer.h#L414 is the complete documentation. Basically it consists of a sequence of chunks being described from line 415 to 455. The format of each chunk is described from line 457 on. There should be no reverse engineering needed.
As it is work in progress there is no explicit documentation - yet...

**Comment by eyck** [comment]
I added some [verbal description](https://github.com/minres/lwTR4SC/#fast-transaction-recording-ftr-format-description) in the hope it helps to understand the FTR format.
